### PR TITLE
Fix parsing failure for partially empty allowedValueList

### LINKED ISSUE #9: SCPD fails when an allowedValueRange maximum is an empty string
In trying to set up a system with a friend's router (so I am unable to rigorously test), I found that when parsing StateVariables when calling `service.scpd()`, I got this error: Invalid response: cannot parse integer from empty string

Turns out, in their WANIPConn1 service, the Uptime state variable had no maximum defined. Specifically:

```
<stateVariable sendEvents="no">
  <name>Uptime</name>
  <dataType>ui4</dataType>
  <defaultValue>0</defaultValue>
  <allowedValueRange>
    <minimum>0</minimum>
    <maximum/>
    <step>1</step>
  </allowedValueRange>
</stateVariable>
```

When parsing, `maximum` here causes the parsing to fail.

The specific router is a TP-Link TD-W9970, model number 4.0.
It also reproduces on the TP-Link Archer VR1600v (unknown model version)

I'm not sure how this would best be represented, but if informed how to I'm happy to do a PR myself.

The specific error location is in `scpd::state_variable::range_from_xml()` when parsing maximum by calling `utils::parse_node_text()`.

### PR DESCRIPTION
**Pull request by Silvea12**
Fixes #9

### CODE REVIEW

**Comment by Silvea12** [comment]
If this looks good, it's ready to merge. However if we wish to pick a different solution I can change it up.

**Comment by jakobhellermann** [comment]
Looks good to me. As far as I can tell this isn't even a breaking change since the field isn't public, so I can release this as a `1.1.x` release.

**Comment by Silvea12** [comment]
It is public API, and is accessible like so:

```
    let scpd = service.scpd(&root_device.url()).await?;
    let f = match scpd.state_variables()[0].kind() {
        StateVariableKind::Range(range) => {
            // Oops!
        }
        _ => {}
    };
```

**Comment by jakobhellermann** [comment]
Hm, in that case I guess this needs to be a `2.0.0` release.

**Comment by Silvea12** [comment]
Actually... I wonder if it'd be worth adding a .map(|e| e.as_str()) to the exposed range so we don't accidentally release a String out, even if it is still a ref.

I might do that tomorrow if you're willing to hold off on the release - I'll tack it onto this PR if it gets unmerged, as it'd be a cleaner API surface.

If you have any other thoughts I'd be happy to do so.

**Comment by jakobhellermann** [comment]
I did the `String -> &str` change in <https://github.com/jakobhellermann/rupnp/commit/8c5b280fe75b5861a9afdac6c81ace776780e570>.
I'm in no rush to release the new version, if you have any other ideas for breaking changes now's a good time, otherwise let me when the interface seems good to you and you'd like a release.

**Comment by Silvea12** [comment]
Honestly nothing comes to mind. Using this is pretty ergonomic, at least in spite of _certain vendors_, and the only other change I could think of would be a bit of a job to do, as it'd require implementing conversions for every data type - some of which aren't available in standard rust and would require pulling in crates like `fixed` for fixed-point numbers, `chrono` or `time` for time and timezone'd values, etc - so I'd say this is probably fine for a 2.0.0, unless that's something you'd want done before a full version bump as it's a non-trivial change.

Though as this kind of change is outside my use case and this is now stable in spite of this vendor misbehavior, which was my goal... I'd say this is probably good, as I'm not planning to personally volunteer for this degree of sweeping change.

**Pull request merged**
